improve docker install script

diff --git a/.chezmoiscripts/run_once_before_install_docker.sh.tmpl b/.chezmoiscripts/run_once_before_install_docker.sh.tmpl
--- a/.chezmoiscripts/run_once_before_install_docker.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_install_docker.sh.tmpl
@@ -1,3 +1,10 @@
 #!/bin/bash
 
-sudo sh -c "$(curl -fsLS get.docker.com)" -- --no-autostart
+if ! command -v docker >/dev/null 2>&1; then
+  echo
+  echo ">>>docker could not be found, starting installation"
+  echo
+  sudo sh -c "$(curl -fsLS get.docker.com)" -- --no-autostart
+  echo
+  sudo usermod -aG docker $USER
+fi
